<?php
/*function Sum (int...$Num):int
 {
return array_sum($Num);
}
echo Sum (1,2,3,4,5);

$phneNumber ='+218910000000';
$regax = '/^\+2189[1234][0-9]{7}$/';

if(preg_match($regax,$phneNumber)) {
    echo 'Valid Libyan Phone number.';
} else{
    echo 'Invaild Libyan phone number.';
}
$username= $_POST ['username'];
$password = $_POST['password'];
print_r($_POST);


if ($_SERVER["REQUEST_METHOD"] == "POST"){
    $targetDir = "./";
    $targetFile =$targetDir.basename($_FILES["file"]["name"]);
    if (move_uploaded_file($_FILES["file"]["tmp_name"],$targetFile)){

        echo"the file has been uplodade";
    } else{
                echo "sorry, there was an error uploading your file.";
        }
    
}


/*$handle = fopen("Example.txt", "w");
fwrite($handle,"Hello,PHP Handling!");
if(file_exists($handle)){
    echo"The file $handle exits";
}else{
    echo "The file $handle does not exits";
}*/

$name = $_POST['username'];
$password = $_POST['password'];

/*
print_r($_POST);

if($_SERVER["REQEST_METHOD"]== "POST")
{
    $comment = $_POST['comment'];
    if (file_exists("Example.txt")){
        
    }
}*/
?>
